title: LiFE - Linear Fascicle Evaluation
description: Evaluation and statistical inference for living connectomes.
google_analytics: UA-15645039-6
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
